### ISSUE TITLE
[BUG] TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by KohnoseLami** [interactions-py/paginator#42]
**Describe the bug**
Use Paginator to send messages and throw errors on all messages after a few minutes
Also, if you call two Paginators and press the buttons for two messages at about the same time, one of them will not respond.

**To Reproduce**
1. Send two Paginators
2. wait a few minutes
3. One of them will have the button edited to disabled, and one of them will print an error.

**Expected behavior**
All Paginator components are disabled

**Traceback**
```py
Traceback (most recent call last):
  File "D:\Desktop\Projects\NX\main.py", line 338, in help_
    await Paginator(
  File "C:\Users\ikki1\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\ext\paginator\paginator.py", line 299, in run
    await self.end_paginator()
  File "C:\Users\ikki1\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\ext\paginator\paginator.py", line 439, in end_paginator
    await self.message.edit(
  File "C:\Users\ikki1\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\models\message.py", line 436, in edit
    message_id=int(self.id),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Toricane** [comment]
1. The issue is because of a bug with stable interactions.py that sometimes occurs since the message I'd isn't given for some reason, but i think it was fixed some time in unstable
2. Update wait_for since i PR'd a fix for the multiple paginators not working, update to 1.0.6 (i believe)

**Comment by KohnoseLami** [comment]
We updated it, we implemented it, and it did improve.
Thank you!
