### ISSUE TITLE
[BUG] TypeError when paginator times out after message is deleted

### ISSUE THREAD

**Issue by ItsRqtl** [interactions-py/paginator#43]
**Describe the bug**
Paginator throwing exceptions.

**To Reproduce**
1. Send a paginator
2. Delete the paginator in discord
3. Wait for timeout

**Expected behavior**
No exceptions being thrown

**Traceback**
```py
Task exception was never retrieved
future: <Task finished name='Task-40' coro=<general.check() done, defined at d:\development\dcusc\cogs\general.py:27> exception=TypeError("int() argument must be a string, a bytes-like object or a real number, not 'NoneType'")>
Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\ext\paginator\paginator.py", line 291, in run
    self.component_ctx: ComponentContext = await wait_for_component(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\ext\wait_for\wait_for.py", line 205, in wait_for_component
    return await wait_for(bot, "on_component", check=_check, timeout=timeout)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\ext\wait_for\wait_for.py", line 109, in wait_for
    res: tuple = await asyncio.wait_for(fut, timeout=timeout)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\development\dcusc\cogs\general.py", line 53, in check
    await Paginator(client=self.client, ctx=ctx, pages=pages, use_select=False, author_only=True).run()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\ext\paginator\paginator.py", line 299, in run
    await self.end_paginator()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\ext\paginator\paginator.py", line 439, in end_paginator
    await self.message.edit(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\api\models\message.py", line 1015, in edit
    message_id=int(self.id),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
**Additional context**
Seems like Paginator is trying to locate the deleted message and disable the buttons.

**Comment by Toricane** [comment]
Are you using the latest unstable version?

**Comment by XxRyanTheLionxX** [comment]
um yes

**Comment by Toricane** [comment]
Ohh it errors on delete, thanks I will fix

**Comment by XxRyanTheLionxX** [comment]
now it also happens on Paginator that isn't deleted (it didn't disable the buttons, just unable to interact after timeout)

**Comment by Toricane** [comment]
Please make sure you are using the unstable branch since I had fixed that
Try uninstalling and reinstalling

**Comment by XxRyanTheLionxX** [comment]
by doing `pip install git+https://github.com/interactions-py/paginator.git@unstable`?

**Comment by Toricane** [comment]
first `pip uninstall dinteractions-Paginator` then do that

**Comment by XxRyanTheLionxX** [comment]
same error occurs. it seems to be installing the same version with `pip install dinteractions-Paginator` and `pip install git+https://github.com/interactions-py/paginator.git@unstable` which is 2.0.2

**Comment by Toricane** [comment]
Nono, i said *uninstall*
yeah the version is the same since I haven't changed the number but the code is different

**Comment by XxRyanTheLionxX** [comment]
I did uninstall (`pip uninstall dinteractions-Paginator`) before installing which is still the same

**Comment by Toricane** [comment]
Ok thanks, I will investigate this later

**Comment by Toricane** [comment]
Sorry for the delay
Should be fixed
Feel free to open the issue again if you still experience it
